before_script:
  - pwd
after_script:
    - echo 'after'
stages:
    - pre_install
    - build
    - deploy
    - reset
    - clean

pre_install_job_1:
  stage: pre_install
  script:
    - mkdir /tmp/build
    - sudo cp -rf ./* /tmp/build
    - cd /tmp/build
    - sudo npm run prestart
    - sudo npm install grunt grunt-contrib-coffee grunt-contrib-cssmin grunt-contrib-htmlmin  grunt-contrib-jshint  grunt-contrib-nodeunit grunt-contrib-uglify  grunt-ts
    - sudo npm install -g typings tsc concurrently  lite-server typescript
    - sudo typings install
  when: on_success
  tags:
    - vertederodev

build_job_2:
  stage: build
  script:
    - cd /tmp/build
    - sudo npm run tsc -w
    - sudo npm run build
  when: on_success
  tags:
    - vertederodev

deploy_job_3:
  stage: deploy
  script:
    - cd /tmp/build
    - sudo cp -rf build/* ./
    - sudo find ./ -type f -name '*.ts' -delete
    - sudo tar -cvf /var/www/html.tar /var/www/html    
    - sudo rm -rf /var/www/html/*
    - sudo cp -rf ./ /var/www/html/
    - sh /home/ubuntu/Vertedero/conn.sh
  when: on_success 
  tags:
    - vertederodev  

reset_job_4:
  stage: reset
  script:
    - sudo rm -rf /tmp/build
    - sudo rm -rf /var/www/html/build
    - sudo rm -rf /var/www/html/typings
    - sudo rm -rf /var/www/html/consultas
    - sudo rm -rf /var/www/html/.git
    - sudo rm -f /var/www/html/.gitignore
    - sudo rm -f /var/www/html/.gitlab-ci.yml
    - sudo rm -f /var/www/html/bs-config.json
    - sudo rm -f /var/www/html/Gruntfile.js
    - sudo rm -f /var/www/html/package.json
    - sudo rm -f /var/www/html/tsconfig.json
    - sudo rm -f /var/www/html/typings.json
  when: always
  tags:
    - vertederodev
    
clean_job_:
  stage: clean
  script:
    - sudo rm -rf /tmp/build
    - sudo rm -rf /var/www/html/*
    - sudo tar -xvf /var/www/html.tar -C /var/www/
  when: on_failure
  tags:
    - vertederodev