before_script:
  - pwd
  - npm version

after_script:
    - echo 'after'
stages:
    - pre_install
    - build
    - deploy
    - clean

pre_install_job:
  stage: pre_install
  script:
    - npm prestart
    - npm install grunt grunt-contrib-coffee grunt-contrib-cssmin grunt-contrib-htmlmin  grunt-contrib-jshint  grunt-contrib-nodeunit grunt-contrib-uglify  grunt-ts
    - sudo npm install -g typings tsc concurrently  lite-server typescript
    - typings install
    - mkdir /tmp/build
    - sudo cp -rf ./* /tmp/build
  when: on_success
  
build_job:
  stage: build
  script:
    - cd /tmp/build
    - sudo npm run tsc -w
    - npm run build
  when: on_success
  
deploy_job:
  stage: deploy
  script:
    - cd /tmp/build
    - sudo cp -rf build/* ./
    - sudo find ./ -type f -name '*.ts' -delete
    - sudo rm -rf /var/www/html/*
    - sudo cp -rf ./ /var/www/html/
    - sh /home/ubuntu/Vertedero/conn.sh
  when: on_success 
  
  
clean_job:
  stage: clean
  script:
    - sudo rm -rf /tmp/build
  when: on_failure