before_script:
  - pwd
  - npm version

after_script:
    - echo 'after'
stages:
    - pre_install
    - build
    - deploy
    - clean
    - update_version

    
update_version_job:
  stage: update_version
  script:
    - echo 'Job Build'   
  tags:
    - vertederodev


pre_install_job:
  stage: pre_install
  script:
    - npm install 
    - npm install grunt grunt-contrib-coffee grunt-contrib-cssmin grunt-contrib-htmlmin  grunt-contrib-jshint  grunt-contrib-nodeunit grunt-contrib-uglify  grunt-ts
    - npm install typings tsc concurrently  lite-server typescript
    - typings install
  when: on_success
  
build_job:
  stage: build
  script:
    - npm run tsc -w
    - npm run build
  when: on_success 
  
  
  
deploy_job:
  stage: deploy
  script:
    - cp -rf build/* ./
    - find ./ -type f -name '*.ts' -delete
    - rm -rf /var/www/html/*
    - mv ./ /var/www/html/
    - sh /home/ubuntu/Vertedero/conn.sh
  when: on_success 
  
  
clean_job:
  stage: clean
  script:
    - rm -rf build/*
  when: on_failure
